name: Push to docker hub

on:
  push:
    branches: [ production ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set DateTime
      run: echo "CURRENT_DATETIME=$(date +%F_%H-%M-%S)" >> $GITHUB_ENV
    
    - name: Build the Docker image
      working-directory: ./SimpleApi/SimpleApi
      run: docker build . --file "SimpleApi/Dockerfile" --tag "simple-api:${CURRENT_DATETIME}" .
    
    - name: Login to Docker Hub
      env: 
        ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: docker login --username gldnpz --password $ACCESS_TOKEN
    
    - name: Push to registry
      run: docker push "gldnpz/simple-api:${CURRENT_DATETIME}"
